-- 身份上下文：用户与刷新令牌（首版认证闭环）
-- 约定：DDL 类型与 Hibernate 7 校验（ddl-auto=validate）严格对齐
--   Instant    -> TIMESTAMP WITH TIME ZONE
--   IDENTITY   -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   boolean    -> BOOLEAN

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)               NOT NULL,
    password_hash VARCHAR(100)              NOT NULL,
    display_name  VARCHAR(64)               NOT NULL,
    email         VARCHAR(128),
    mfa_enabled   BOOLEAN                   NOT NULL DEFAULT FALSE,
    totp_secret   VARCHAR(64),
    status        VARCHAR(16)               NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE  NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE  NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                      NOT NULL REFERENCES users (id),
    token_hash VARCHAR(64)                 NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE    NOT NULL,
    revoked    BOOLEAN                     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE    NOT NULL,
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
