-- 全量表结构：认证扩展（6 张）+ 业务域（8 张），一次建齐
-- 约定与 V1 一致：Instant -> TIMESTAMP WITH TIME ZONE；IDENTITY -> BIGINT GENERATED BY DEFAULT AS IDENTITY

-- ============ 认证扩展 ============

-- 个人信息：users 只管认证凭据，个人资料独立 1:1 扩展
CREATE TABLE user_profiles (
    user_id       BIGINT PRIMARY KEY REFERENCES users (id),
    avatar        VARCHAR(255),
    phone         VARCHAR(20),
    department    VARCHAR(64),
    title         VARCHAR(64),
    bio           VARCHAR(512),
    last_login_at TIMESTAMP WITH TIME ZONE,
    last_login_ip VARCHAR(45),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 第三方登录绑定（GitHub/OIDC/SAML/CAS/钉钉/飞书/企业微信）
CREATE TABLE user_third_party (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT                      NOT NULL REFERENCES users (id),
    provider         VARCHAR(16)                 NOT NULL,
    provider_user_id VARCHAR(128),
    nickname         VARCHAR(64),
    avatar_url       VARCHAR(255),
    bound_at         TIMESTAMP WITH TIME ZONE    NOT NULL,
    CONSTRAINT uk_third_party_user_provider UNIQUE (user_id, provider)
);

-- SSO 提供商 OAuth 客户端配置（client secret 加密存储）
CREATE TABLE sso_providers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider            VARCHAR(16)   NOT NULL,
    display_name        VARCHAR(64)   NOT NULL,
    enabled             BOOLEAN       NOT NULL DEFAULT FALSE,
    client_id           VARCHAR(128),
    client_secret_enc   TEXT,
    authorize_url       VARCHAR(255),
    token_url           VARCHAR(255),
    userinfo_url        VARCHAR(255),
    scopes              VARCHAR(255),
    extra_config        JSONB,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_sso_providers_provider UNIQUE (provider)
);

-- 用户 MFA 补充设置：短信 / 邮件验证码绑定
CREATE TABLE user_security_settings (
    user_id           BIGINT PRIMARY KEY REFERENCES users (id),
    sms_phone         VARCHAR(20),
    sms_enabled       BOOLEAN NOT NULL DEFAULT FALSE,
    email_mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

-- MFA 恢复码（仅存哈希）
CREATE TABLE recovery_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                      NOT NULL REFERENCES users (id),
    code_hash  VARCHAR(64)                 NOT NULL,
    used       BOOLEAN                     NOT NULL DEFAULT FALSE,
    used_at    TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE    NOT NULL
);
CREATE INDEX idx_recovery_codes_user ON recovery_codes (user_id, used);

-- WebAuthn / Passkey 设备
CREATE TABLE webauthn_credentials (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT                      NOT NULL REFERENCES users (id),
    credential_id VARCHAR(255)                NOT NULL,
    public_key    TEXT                        NOT NULL,
    sign_count    BIGINT                      NOT NULL DEFAULT 0,
    name          VARCHAR(64),
    added_at      TIMESTAMP WITH TIME ZONE    NOT NULL,
    CONSTRAINT uk_webauthn_credential UNIQUE (credential_id)
);

-- ============ 业务域 ============

-- 凭据（敏感内容 AES 加密存储，另存脱敏展示串）
CREATE TABLE credentials (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(64)   NOT NULL,
    type             VARCHAR(16)   NOT NULL,
    secret_encrypted TEXT          NOT NULL,
    secret_masked    VARCHAR(64),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 资产清单
CREATE TABLE assets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64)   NOT NULL,
    type        VARCHAR(16)   NOT NULL,
    address     VARCHAR(128)  NOT NULL,
    protocol    VARCHAR(16)   NOT NULL,
    port        INTEGER,
    group_path  VARCHAR(255)  NOT NULL DEFAULT '未分组',
    description VARCHAR(512),
    status      VARCHAR(16)   NOT NULL DEFAULT 'active',
    created_by  BIGINT REFERENCES users (id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_assets_type ON assets (type);
CREATE INDEX idx_assets_protocol ON assets (protocol);

-- 资产账号（资产上的登录账号）
CREATE TABLE asset_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id      BIGINT      NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
    name          VARCHAR(64) NOT NULL,
    type          VARCHAR(16) NOT NULL,
    privileged    BOOLEAN     NOT NULL DEFAULT FALSE,
    source        VARCHAR(16) NOT NULL DEFAULT 'manual',
    credential_id BIGINT REFERENCES credentials (id) ON DELETE SET NULL,
    enabled       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_asset_accounts UNIQUE (asset_id, name)
);

-- 授权策略（资产/账号范围用 JSONB 存 id 数组）
CREATE TABLE access_policies (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64) NOT NULL,
    user_id     BIGINT      NOT NULL REFERENCES users (id),
    asset_ids   JSONB       NOT NULL DEFAULT '[]',
    account_ids JSONB       NOT NULL DEFAULT '[]',
    protocol    VARCHAR(16),
    valid_from  TIMESTAMP WITH TIME ZONE,
    valid_to    TIMESTAMP WITH TIME ZONE,
    status      VARCHAR(16) NOT NULL DEFAULT 'pending',
    description VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_access_policies_user ON access_policies (user_id);

-- 会话（在线状态 + 录像元数据）
CREATE TABLE sessions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT      NOT NULL REFERENCES users (id),
    asset_id             BIGINT      NOT NULL REFERENCES assets (id),
    account_id           BIGINT REFERENCES asset_accounts (id),
    protocol             VARCHAR(16) NOT NULL,
    status               VARCHAR(16) NOT NULL,
    source_ip            VARCHAR(45),
    started_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at             TIMESTAMP WITH TIME ZONE,
    recording_path       VARCHAR(255),
    recording_size_bytes BIGINT
);
CREATE INDEX idx_sessions_user ON sessions (user_id);
CREATE INDEX idx_sessions_status ON sessions (status, started_at DESC);

-- 操作审计日志
CREATE TABLE audit_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL REFERENCES users (id),
    asset_id       BIGINT REFERENCES assets (id),
    account_id     BIGINT REFERENCES asset_accounts (id),
    action         VARCHAR(64) NOT NULL,
    command_detail TEXT,
    result         VARCHAR(16) NOT NULL,
    risk           VARCHAR(16) NOT NULL,
    source_ip      VARCHAR(45),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_audit_logs_time ON audit_logs (created_at DESC);
CREATE INDEX idx_audit_logs_risk ON audit_logs (risk);

-- 登录日志（认证埋点写入）
CREATE TABLE login_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT REFERENCES users (id),
    username   VARCHAR(64) NOT NULL,
    source_ip  VARCHAR(45),
    location   VARCHAR(64),
    method     VARCHAR(16) NOT NULL,
    result     VARCHAR(16) NOT NULL,
    reason     VARCHAR(128),
    client     VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_login_logs_time ON login_logs (created_at DESC);
CREATE INDEX idx_login_logs_result ON login_logs (result);

-- 系统设置：五个分组各一行 JSONB
CREATE TABLE settings (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section VARCHAR(16) NOT NULL,
    config  JSONB       NOT NULL,
    CONSTRAINT uk_settings_section UNIQUE (section)
);
