-- V6：网关接入扩展 —— AI 异常检测落库表。
-- 说明：sessions 表的录像字段（recording_path/recording_size_bytes）在 V2 已建，
-- 本迁移只补 Python 检测服务与 Java 管理服务共享的异常记录表。

-- AI 异常检测结果（Python 服务写入，Java 管理服务查询/处置）
CREATE TABLE audit_anomalies (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users (id),
    session_id   BIGINT REFERENCES sessions (id),
    asset_id     BIGINT REFERENCES assets (id),
    account      VARCHAR(64),
    command      TEXT NOT NULL,
    anomaly_type VARCHAR(16) NOT NULL,
    score        DOUBLE PRECISION NOT NULL,
    detail       VARCHAR(255),
    status       VARCHAR(16) NOT NULL DEFAULT 'new',
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_audit_anomalies_time ON audit_anomalies (created_at DESC);
CREATE INDEX idx_audit_anomalies_user ON audit_anomalies (user_id);
